DataDog/dd-native-appsec-js

.github/workflows/build_and_release.yml
package.json

update libddwaf to 1.0.13

---

LICENSE-3rdparty.csv
scripts/check_licenses.js

add libddwaf license

---

.github/workflows/build_and_release.yml

update to windows latest

---

src/convert.cpp
test/index.js
test/rules.json

add a unit test for an edge case

Support booleans

---

.github/workflows/build_and_release.yml
index.d.ts
package.json
src/log.h
src/main.cpp
test/index.js

update to libddwaf 1.0.16

---

.github/workflows/build_and_release.yml
.gitmodules
package-lock.json
test/fuzz.js
test/index.js
test/rules.json

add string fuzzing

---

.github/workflows/build_and_release.yml
docker/Dockerfile
docker/alpine.Dockerfile
package-lock.json
package.json

This makes the build process actually work as intended
Building process broke on windows because of Visual Studio 2022, and I discovered that we weren't using the intended version of `node-gyp`. Then I had to install a recent version of python to make it work with the never `node-gyp` version

Fix build process

---

package-lock.json
package.json

Update minimist dependency to 1.2.6
CVE found in the current version

update minimist to 1.2.6

---

.github/workflows/build_and_release.yml
index.d.ts
package.json
src/main.cpp
test/index.js
test/rules.json

Update libddwaf to 1.2.1 and make the necessary changes to keep it working, ie: change the result's perf field and add nullptr for later

update libddwaf to 1.2.1

---

src/main.cpp

This adds missing libddwaf free functions
Memory leaks were reported by users

free `rules` `data` and `results`

---

binding.gyp
index.d.ts
package.json
src/main.cpp
src/main.h
test/index.js
test/rules.json

Updates libddwaf to 1.5.1
https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md

Update libddwaf to 1.5.1

---

index.d.ts
src/convert.cpp
src/convert.h
src/main.cpp
src/main.h
test/index.js

Adds the ability to toggle rules.
As part of ASM product, a way to toggle rules in the WAF is needed in order to apply the values coming from `rules_override`.

Add toggle_rules

---

src/main.cpp

Call the free functions in better places.

Better memory freeing

---

package.json

Update ddwaf version to 1.7.0

---

index.d.ts
src/main.cpp
src/main.h
test/index.js

Implements the `ddwaf_required_address` function, and exposes the value in JS land as a Set.

Implement `ddwaf_required_addresses`

---

package.json

Update libddwaf to 1.10.0

---

.github/workflows/build.yml
.github/workflows/release.yml
package-lock.json
package.json

Do automatic releases upon tag creation:
- Tags must comply with the following regex: `v[0-9]+.[0-9]+.[0-9]+`
- `create_release` and `publish` jobs works under `release` and `npm` environments respectively.
- `release` and `npm` environments has rules and need approval from appsec-js team before being executed.

Automatic release

---

.github/workflows/release.yml

Add the provenance arg to npm publish, to enable package publication signing.
Better supply chain security

Add NPM provenance

---

.github/workflows/build.yml
index.d.ts
src/convert.cpp
src/convert.h
src/main.cpp
test/index.js
test/processor.json
test/rules.json

Add support for processor's result collection. 
Needed for integrating API security since schema extraction is returned in `derivatives` property.
Closes #43

Add derivatives support [APPSEC-11114]

---

scripts/setup.js

Hardcodes a bit more the list of libddwaf builds to download.
It was prioritizing builds with latter alphabetical index.

Narrows list of builds to download

---

.github/workflows/build.yml
.github/workflows/release.yml

Fix the prebuildify action by using commas instead of spaces for skipping architectures.

Fix prebuildify action

---

package.json

Update libddwaf to 1.20.1

---

package.json

Update libddwaf to 1.22.0

---

package-lock.json
package.json

bump package to v8.4.0

---

index.d.ts
src/convert.cpp
src/convert.h
src/main.cpp
src/main.h
src/metrics.h
test/index.js

Report WAF errors and max truncated elements

report max truncated elements and errors
