src/convert.cpp, test/index.js, test/rules.json
Adding a limit to the number of properties per object. There is now a single biggest object allowed by the bindings
=> limit number of entries allowed in objects

src/main.cpp
Better manage the memory of the obfuscator's strings.
=> Better manage the obfuscator config memory

lib/loader.js
Replace `os` methods by the cached `process` properties
=> Replace `os.plateform()`  and `os.arch()`

.github/workflows/build_and_release.yml, package.json
Hardcode the version of the windows image used in CI to `windows-2019`
`windows-latest` uses a version of msvc that seems incompatible with `libddwaf` builds.
=> Use `windows-2019` images in CI

.github/workflows/release.yml
Use codex-team/action-nodejs-package-info@v1.1
The release workflow raised and error:
codex-team/action-nodejs-package-info@v1 is not allowed to be used in DataDog/dd-native-appsec-js. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: codex-team/action-nodejs-package-info@v1.1.
=> Use codex-team/action-nodejs-package-info@v1.1

package-lock.json, package.json
Adds new version in order to release the suppport for the derivatives feature needed to API Security.
=> Version 4.1.0

index.d.ts, package.json, src/alloca.h, src/main.cpp, src/main.h, test/fuzz.js, test/index.js, test/rules.json
This PR updates the libddwaf version to 1.15.1. It contains breaking API changes:
* Add a new parameter to handle the whole payload: persistent and ephemeral addresses.
* Change function 'ddwaf_required_addresses' to 'ddwaf_known_addresses'.
[APPSEC-12207]
[APPSEC-12283]: https://datadoghq.atlassian.net/browse/APPSEC-12207
[APPSEC-12207]: https://datadoghq.atlassian.net/browse/APPSEC-12207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update waf version to 1.15.1

.eslintrc.json, .github/workflows/build.yml, .github/workflows/release.yml, README.md, package-lock.json, package.json, src/main.cpp, test/worker.js, test/worker_threads.js
@simon-id , please add some tests when you have a way to reproduce the issue
=> Updates node-addon-api

src/convert.cpp, src/convert.h, test/index.js
When converting objects and arrays, if the `toJSON()` method is present, call it and use it as result
=> use toJSON() property when it exists

src/convert.cpp, src/convert.h, src/jsset.h, test/index.js
Prevents circular dependencies when an object is converted to ddwaf object. If the circular dependency is detected, it replaces the circular dependency by `invalid` object.
Prevent infinite or too long iterations
[APPSEC-51953]
[APPSEC-51953]: https://datadoghq.atlassian.net/browse/APPSEC-51953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent circular dependencies

src/convert.cpp, src/convert.h
Remove the depth limits when decoding ddwaf_objects
API Security was being truncated
=> Remove depth limits in `from_ddwaf_object()`

.github/workflows/build.yml, .github/workflows/release.yml, README.md, package-lock.json, package.json, src/main.cpp
Update package version to v8.0.0
Change NodeJS supported version to >= 16
Upgrade to the new version 1.18.0 (from 1.16.0) of `libddwaf`.
Drop support for Node 14
`libddwaf 1.17.0` includes a breaking change because the actions field of the result is no longer a string array but a map.
=> v8.0.0 + drop support for NodeJs 14

.github/workflows/release.yml
Retrieve only `prebuilds` artifact from `prebuildify` job
Get a valid package.
=> Download only `prebuilds` folder from `prebuildify` job

index.d.ts, package.json, src/main.cpp, src/main.h, test/index.js
Bump libddwaf to 1.19.1 and implement the new `ddwaf_known_actions` method
=> Bump libddwaf to 1.19.1

.github/workflows/release.yml
Fix release workflow, including the correct folder structure for prebuilds.
Get a valid package published
This fix is due to some changes in prebuildify action when merging artifacts.
=> Fix release workflow - include correct prebuilds in package

.github/workflows/release.yml
Set `contents: write` permission in `create_release` job
After changing the default workflow permissions in the repo, it is necessary to adjust the permissions in the workflow file.
[Create release endpoint doc](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release)
=> Set `GITHUB_TOKEN` permissions for `create_release` job in `release` workflow

src/convert.cpp, test/index.js
Handle `toJSON` errors gracefully with null value as a fallback
When `toJSON` throws an error, the application currently stops with a fatal error. 
This PR changes the behavior so that instead of crashing, we fall back to `null` if an error occurs while executing `toJSON`
=> handle case when tojson throws an error

.github/workflows/build.yml, scripts/setup.js
Use the automatically created token from GitHub Actions to download `libddwaf` lib from its repo.
=> Fix libddwaf lib download

index.d.ts, package.json, src/convert.cpp, src/convert.h, src/main.cpp, test/index.js
- Update `libddwaf` to v1.26.0 from v1.24.1
- Implements new `ddwaf_run` result
- Changes some result properties names in JS result object:
- `derviatives` for `attributes`
- `totalRuntime` for `duration`
- New result property `keep`
`libddwaf` v1.25.0 removes `ddwaf_result` structure, which has been replaced by a `ddwaf_object`, with some changes in its structure.
[Upgrading guide](https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md)
[APPSEC-57562](https://datadoghq.atlassian.net/browse/APPSEC-57562)
[APPSEC-57562]: https://datadoghq.atlassian.net/browse/APPSEC-57562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update`libddwaf` to v1.26.0

src/convert.cpp, test/index.js, test/rules.json
Add support for all ddwaf_object types in `from_ddwaf_object`
Cover all the possible object types in ddwaf_object marshalling
Fixes #76
=> Add support for all ddwaf_object types in `from_ddwaf_object`
